name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel ${{ vars.VERCEL_PROD_FLAG }} ${{ vars.VERCEL_YES_FLAG }} --token ${{ secrets.VERCEL_TOKEN }} ${{ vars.VERCEL_CONFIRM_FLAG }} --name ${{ secrets.VERCEL_PROJECT_NAME }} --scope ${{ secrets.VERCEL_TEAM }}

      - name: Smoke Tests
        run: |
          FAILED=0

          if ! curl -f ${{ vars.BASE_URL }}  ; then
            FAILED=1
          fi

          OVERVIEW_RESPONSE=$(curl -s ${{ vars.BASE_URL }}${{ vars.USED_CARS_OVERVIEW_API_ENDPOINT }})
          if [ -z "$OVERVIEW_RESPONSE" ]; then
            FAILED=1
          else
            FIRST_ID=$(echo $OVERVIEW_RESPONSE | jq -r "${{ vars.JSON_PATH_FIRST_USED_CAR_ID }} // empty")
            if [ -n "$FIRST_ID" ]; then
              if ! curl -f "${{ vars.BASE_URL }}${{ vars.USED_CAR_INFO_API_ENDPOINT }}?id=$FIRST_ID" ; then
                FAILED=1
              fi
            fi
          fi

          if [ $FAILED -eq 1 ]; then
            PREV_DEPLOY=$(npx vercel list ${{ secrets.VERCEL_PROJECT_NAME }} --token ${{ secrets.VERCEL_TOKEN }} --prod --scope ${{ secrets.VERCEL_TEAM }} | sed -n '2p' | awk '{print $1}')
            npx vercel rollback $PREV_DEPLOY --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_TEAM }}
            exit 1
          fi

          echo "All smoke tests passed."
