name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ vars.SONAR_FETCH_DEPTH }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run Lint and Prettier
        run: npm run code:check

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test -- --watchAll=${{ vars.TEST_WATCH_ALL }}

      - name: Run npm audit
        run: npm audit --audit-level=${{ vars.AUDIT_LEVEL }}

      - name: Run SonarQube analysis
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.sources=${{ vars.SONAR_SOURCES }}
            -Dsonar.exclusions=${{ vars.SONAR_EXCLUSION }}
            -Dsonar.qualitygate.wait=${{ vars.SONAR_QUALITY_GATE_WAIT }}
